Added Repetition.py
CodeChef-SMVDU/Solve-It pull request #6
Opened 2020-10-02 13:50 UTC by amitagarwalaa57

2020-10-05 17:09 UTC, codetheorem requested changes
Use `input()`.

2020-10-05 17:09 UTC, codetheorem commented on Repetitions.py
> +	str = "ATTCGGGA"
Input should be dynamic and not pre-defined.

2020-10-06 03:54 UTC, amitagarwalaa57 commented
made the change.

2020-10-06 04:09 UTC, codetheorem reviewed
ok thanks

2020-10-10 13:13 UTC, merged